[2025-03-06 11:01:22,323] ERROR in app: Missing environment variables: SECRET_KEY, WTF_CSRF_SECRET_KEY, RDS_DATABASE_URI, S3_BUCKET, S3_KEY, S3_SECRET, S3_REGION
[2025-03-06 11:13:20,279] ERROR in app: Missing environment variables: SECRET_KEY, WTF_CSRF_SECRET_KEY, RDS_DATABASE_URI, S3_BUCKET, S3_KEY, S3_SECRET, S3_REGION
[2025-03-06 11:18:15,384] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\benji\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\benji\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\benji\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 878, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Users\benji\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1253, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "C:\Users\benji\Downloads\xero_test_new_5\app.py", line 129, in make_session_permanent
    session.permanent = True
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\benji\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\sessions.py", line 34, in permanent
    self["_permanent"] = bool(value)
    ~~~~^^^^^^^^^^^^^^
  File "C:\Users\benji\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\sessions.py", line 102, in _fail
    raise RuntimeError(
    ...<3 lines>...
    )
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
[2025-03-06 11:18:19,576] ERROR in app: Exception on /register [GET]
Traceback (most recent call last):
  File "C:\Users\benji\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\benji\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\benji\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 878, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Users\benji\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1253, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "C:\Users\benji\Downloads\xero_test_new_5\app.py", line 129, in make_session_permanent
    session.permanent = True
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\benji\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\sessions.py", line 34, in permanent
    self["_permanent"] = bool(value)
    ~~~~^^^^^^^^^^^^^^
  File "C:\Users\benji\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\sessions.py", line 102, in _fail
    raise RuntimeError(
    ...<3 lines>...
    )
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
[2025-03-06 11:19:03,726] ERROR in app: Exception on /register [GET]
Traceback (most recent call last):
  File "C:\Users\benji\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\benji\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\benji\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 878, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Users\benji\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1253, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "C:\Users\benji\Downloads\xero_test_new_5\app.py", line 129, in make_session_permanent
    session.permanent = True
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\benji\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\sessions.py", line 34, in permanent
    self["_permanent"] = bool(value)
    ~~~~^^^^^^^^^^^^^^
  File "C:\Users\benji\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\sessions.py", line 102, in _fail
    raise RuntimeError(
    ...<3 lines>...
    )
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
[2025-03-06 11:19:26,556] ERROR in app: Exception on /register [GET]
Traceback (most recent call last):
  File "C:\Users\benji\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\benji\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\benji\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 878, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Users\benji\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1253, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "C:\Users\benji\Downloads\xero_test_new_5\app.py", line 129, in make_session_permanent
    session.permanent = True
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\benji\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\sessions.py", line 34, in permanent
    self["_permanent"] = bool(value)
    ~~~~^^^^^^^^^^^^^^
  File "C:\Users\benji\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\sessions.py", line 102, in _fail
    raise RuntimeError(
    ...<3 lines>...
    )
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
[2025-03-06 15:23:38,148] ERROR in app: Error during registration: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'xeropettycashtest.cj2ykcm64tbe.ap-northeast-2.rds.amazonaws.com' (timed out)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
[2025-03-07 13:37:35,304] ERROR in app: Error during registration: (pymysql.err.IntegrityError) (1062, "Duplicate entry 'admin22' for key 'username'")
[SQL: INSERT INTO user (first_name, last_name, id, username, password, company, role, approved, reset_token, reset_token_expiry) VALUES (%(first_name)s, %(last_name)s, %(id)s, %(username)s, %(password)s, %(company)s, %(role)s, %(approved)s, %(reset_token)s, %(reset_token_expiry)s)]
[parameters: {'first_name': 'admin22', 'last_name': 'admin22', 'id': '57cd8711-7a84-4e5f-a3b8-2cc75b3fc520', 'username': 'admin22', 'password': 'pbkdf2:sha256:600000$DqADbP4oWO8SSAmZ$c7a4e304e3db7cc0603200df29d14e812bf0dc6cf778d87e438fd3063b126c5e', 'company': 'admin222', 'role': 'admin', 'approved': 0, 'reset_token': None, 'reset_token_expiry': None}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
[2025-03-07 14:04:49,782] INFO in app: Raw form data: {'csrf_token': ['IjBlN2UxNTUwYzIyZmRiYTlmNmVjODlkOWQzYmRkY2M3MzgwYzdlZWMi.Z8qMXA.nmQJwdzqIWM01ikZAvxnirh2t-U'], 'company': ['client'], 'opening_balance': ['0'], 'cash_addition': ['0'], 'transaction_date': ['2025-03-07'], 'sales[shop_sales][cash]': ['500'], 'sales[shop_sales][visa]': [''], 'sales[shop_sales][master]': [''], 'sales[shop_sales][unionpay]': [''], 'sales[shop_sales][alipay]': [''], 'sales[shop_sales][wechat]': [''], 'sales[shop_sales][amex]': [''], 'sales[shop_sales][octopus]': [''], 'sales[delivery_sales][deliveroo]': [''], 'sales[delivery_sales][foodpanda]': [''], 'sales[delivery_sales][keeta]': [''], 'sales[delivery_sales][openrice]': [''], 'bank_deposit': ['0'], 'closing_balance': ['500.00'], 'actual_cash[note1000]': [''], 'actual_cash[note500]': ['1'], 'actual_cash[note100]': [''], 'actual_cash[note50]': [''], 'actual_cash[note20]': [''], 'actual_cash[note10]': [''], 'actual_cash[5coins]': [''], 'actual_cash[2coins]': [''], 'actual_cash[1coins]': [''], 'total_actual_cash_value': ['500.00'], 'actual_cash_value': ['500.00']}
[2025-03-07 14:04:49,792] INFO in app: Raw file data: {}
[2025-03-07 14:04:49,793] INFO in app: Cleaned form data: {'csrf_token': 'IjBlN2UxNTUwYzIyZmRiYTlmNmVjODlkOWQzYmRkY2M3MzgwYzdlZWMi.Z8qMXA.nmQJwdzqIWM01ikZAvxnirh2t-U', 'company': 'client', 'opening_balance': '0', 'cash_addition': '0', 'transaction_date': '2025-03-07', 'sales[shop_sales][cash]': '500', 'sales[shop_sales][visa]': '', 'sales[shop_sales][master]': '', 'sales[shop_sales][unionpay]': '', 'sales[shop_sales][alipay]': '', 'sales[shop_sales][wechat]': '', 'sales[shop_sales][amex]': '', 'sales[shop_sales][octopus]': '', 'sales[delivery_sales][deliveroo]': '', 'sales[delivery_sales][foodpanda]': '', 'sales[delivery_sales][keeta]': '', 'sales[delivery_sales][openrice]': '', 'bank_deposit': '0', 'closing_balance': '500.00', 'actual_cash[note1000]': '', 'actual_cash[note500]': '1', 'actual_cash[note100]': '', 'actual_cash[note50]': '', 'actual_cash[note20]': '', 'actual_cash[note10]': '', 'actual_cash[5coins]': '', 'actual_cash[2coins]': '', 'actual_cash[1coins]': '', 'total_actual_cash_value': '500.00', 'actual_cash_value': '500.00'}
[2025-03-07 14:04:49,799] INFO in app: Checking for existing report with transaction_date: 2025-03-07 for company: client
[2025-03-07 14:10:45,915] INFO in app: Raw file data: {}
[2025-03-07 14:10:45,932] INFO in app: Raw file data: {}
[2025-03-07 14:10:45,958] INFO in app: Checking for existing report with transaction_date: 2025-03-08 for company: client
[2025-03-07 14:10:45,978] INFO in app: Checking for existing report with transaction_date: 2025-03-08 for company: client
[2025-03-07 14:10:45,992] INFO in app: No previous reports found; this is the first report.
